/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualização;

import ModeloBeans.ConsultaBeans;
import ModeloBeans.ProdutoBeans;
import ModeloDAO.ProdutoDAO;

/**
 *
 * @author leslye
 */
public class Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2UnMedida = new javax.swing.JTextField();
        jTextField2Preco = new javax.swing.JTextField();
        jTextField2DataValidade = new javax.swing.JTextField();
        jTextField2NomeConsulta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 30, 120, 31);

        jPanel1.setLayout(null);

        jLabel2.setText("Nome");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 20, 60, 17);

        jLabel3.setText("Un. Medida");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 90, 100, 17);

        jLabel4.setText("Data de Validade");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 60, 100, 17);

        jLabel5.setText("Preço");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 20, 60, 20);

        jTextField2UnMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2UnMedidaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2UnMedida);
        jTextField2UnMedida.setBounds(140, 90, 110, 29);

        jTextField2Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2PrecoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2Preco);
        jTextField2Preco.setBounds(330, 10, 110, 29);

        jTextField2DataValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2DataValidadeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2DataValidade);
        jTextField2DataValidade.setBounds(140, 50, 110, 29);

        jTextField2NomeConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2NomeConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2NomeConsulta);
        jTextField2NomeConsulta.setBounds(140, 10, 110, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 100, 480, 160);

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 238, 238));
        jLabel6.setText("Id");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 30, 50, 26);

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldID);
        jTextFieldID.setBounds(90, 30, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/285845348d6a2c6.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 580, 330);

        setSize(new java.awt.Dimension(591, 334));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextField2UnMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2UnMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2UnMedidaActionPerformed

    private void jTextField2PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2PrecoActionPerformed

    private void jTextField2DataValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2DataValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2DataValidadeActionPerformed

    private void jTextField2NomeConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2NomeConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2NomeConsultaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ConsultaBeans consulta = new ConsultaBeans();
        int id = Integer.parseInt(jTextFieldID.getText());
        
        
        
        ConsultaBeans produtoB = new ConsultaBeans();
        
        consulta.setPesquisa(id);
        ProdutoDAO produto = new ProdutoDAO();
        produtoB = produto.BuscaProduto(consulta);
        
        jTextField2NomeConsulta.setText(produtoB.getNome());
        jTextField2DataValidade.setText(String.valueOf(produtoB.getDtValidade()));
        jTextField2UnMedida.setText(produtoB.getUnMedida());
        jTextField2Preco.setText(String.valueOf(produtoB.getPreco()));
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2DataValidade;
    private javax.swing.JTextField jTextField2NomeConsulta;
    private javax.swing.JTextField jTextField2Preco;
    private javax.swing.JTextField jTextField2UnMedida;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
